In [16]:
import numpy as np

In [17]:
data = np.random.randn(2, 3)

In [18]:
data

array([[ 0.15599048, -1.07217434, -0.45092629],
       [-0.30173953,  1.11603403,  1.03396717]])

In [19]:
data*10

array([[  1.55990475, -10.72174335,  -4.50926292],
       [ -3.0173953 ,  11.16034033,  10.33967167]])

In [20]:
data.shape

(2, 3)

In [21]:
data.dtype

dtype('float64')

In [22]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [26]:
data2 =[[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr2.shape

(2, 4)

In [28]:
np.shape(arr2)

(2, 4)

In [29]:
arr2.ndim

2

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr2.dtype

dtype('int64')

In [37]:
arr3 = np.zeros(10)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
arr3 = np.zeros((3,6))

In [40]:
arr3

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [42]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.empty((2,3))

array([[ 1.55990475, 10.72174335,  4.50926292],
       [ 3.0173953 , 11.16034033, 10.33967167]])

In [44]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
np.full((10,4),"뿡")

array([['뿡', '뿡', '뿡', '뿡'],
       ['뿡', '뿡', '뿡', '뿡'],
       ['뿡', '뿡', '뿡', '뿡'],
       ['뿡', '뿡', '뿡', '뿡'],
       ['뿡', '뿡', '뿡', '뿡'],
       ['뿡', '뿡', '뿡', '뿡'],
       ['뿡', '뿡', '뿡', '뿡'],
       ['뿡', '뿡', '뿡', '뿡'],
       ['뿡', '뿡', '뿡', '뿡'],
       ['뿡', '뿡', '뿡', '뿡']], dtype='<U1')

In [53]:
np.eye

<function numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)>

In [54]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
arr1 = np.array(([1,2,3]), np.float32)

In [84]:
arr1.shape

(3,)

In [87]:
arr = np.array([[1,2,3],[4,5,6]])

In [88]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [89]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [90]:
2/arr

array([[2.        , 1.        , 0.66666667],
       [0.5       , 0.4       , 0.33333333]])

In [91]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
arr *= arr

In [93]:
arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [94]:
arr ** 0.5

array([[1., 2., 3.],
       [4., 5., 6.]])

In [95]:
arr2 = np.random.randn(2,3)

In [96]:
arr2 > arr

array([[ True, False, False],
       [False, False, False]])

In [97]:
arr2

array([[ 1.24948818,  0.75231474,  1.11842148],
       [-0.40136672,  0.97467126,  0.2428257 ]])

In [98]:
arr = np.random.randn(4,3)

In [99]:
arr.mean(0)

array([-0.03457964,  0.45860094, -0.72512744])

In [101]:
demeaned = arr - arr.mean(0)
demeaned

array([[-0.82242122,  0.04329005,  1.27016539],
       [-0.64640453,  0.29805783,  1.07049898],
       [ 1.92713237, -0.14454799, -0.61265426],
       [-0.45830662, -0.19679989, -1.72801012]])

In [102]:
arr = np.arange(10)

In [103]:
arr[5:8]

array([5, 6, 7])

In [105]:
arr.shape

(10,)

In [106]:
arr.dtype

dtype('int64')

In [107]:
arr[:4]

array([0, 1, 2, 3])

In [108]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
arr[5:]

array([5, 6, 7, 8, 9])

In [110]:
arr = range(10)

In [111]:
arr

range(0, 10)

In [112]:
arr[:4]

range(0, 4)

In [115]:
arr = np.arange(10)
arr[3:8]

array([3, 4, 5, 6, 7])

In [120]:
arr = np.random.randn(2,3)
demeaned = arr - arr.mean(0)
demeaned.mean(0)

array([0., 0., 0.])

In [125]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [127]:
arr2d[0,2]

3

In [129]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [130]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [131]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
arr3d[0,1,2]

6

In [171]:
name = np.array(['김가영', '송영훈', '배고파', '사랑해'])
new_arr = np.random.randn(4,4)
new_arr

array([[ 0.8248104 , -0.52070301,  0.89144708, -0.80962708],
       [ 1.01251069,  0.62344823, -0.00757331, -2.27641754],
       [-1.42665342, -1.86517085, -0.83696703,  1.57919226],
       [-0.51083278, -0.7619182 ,  1.04991922,  0.56212437]])

In [174]:
new_arr[name == '김가영']

array([[ 0.8248104 , -0.52070301,  0.89144708, -0.80962708]])

In [176]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [178]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [179]:
x = np.random.randn(8)
x

array([-0.09176658, -1.29950866, -1.4988328 , -0.48231602, -0.52523539,
       -1.90293426, -0.21919252,  0.76447594])

In [180]:
y = np.random.randn(8)
y

array([ 0.36370832,  1.25042795,  1.57134119,  0.37895579,  0.06432779,
       -2.84200894, -0.42106214,  0.05026201])

In [183]:
np.maximum(x, y)#둘 중 큰 수로 구성

array([ 0.36370832,  1.25042795,  1.57134119,  0.37895579,  0.06432779,
       -1.90293426, -0.21919252,  0.76447594])

In [184]:
arr = np.random.randn(7)*5
arr

array([-0.45093124, -1.57298917,  5.87170861, -0.96249685,  4.8042174 ,
        0.26631015,  4.22381818])

In [185]:
remainder, whole_part = np.modf(arr)#몫과 나머지를 분류

In [187]:
remainder#나머지

array([-0.45093124, -0.57298917,  0.87170861, -0.96249685,  0.8042174 ,
        0.26631015,  0.22381818])

In [189]:
whole_part#몫

array([-0., -1.,  5., -0.,  4.,  0.,  4.])

In [190]:
arr

array([-0.45093124, -1.57298917,  5.87170861, -0.96249685,  4.8042174 ,
        0.26631015,  4.22381818])

In [191]:
np.sqrt(arr)#NaN값이 존재해서

<ipython-input-191-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan, 2.42316087,        nan, 2.1918525 ,
       0.51605247, 2.05519298])

In [192]:
np.sqrt(arr, arr)

<ipython-input-192-164954cb2c14>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([       nan,        nan, 2.42316087,        nan, 2.1918525 ,
       0.51605247, 2.05519298])

In [194]:
points = np.arange(-5,5,0.01)
xs, ys = np.meshgrid(points, points)
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [196]:
z = np.sqrt(xs**2 + ys**2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [199]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True, False, True, True, False])

In [200]:
result = [(x if c else y)
         for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [201]:
arr = np.random.randn(4,4)
arr

array([[ 0.22081032,  2.03431575, -1.92921577,  0.47449677],
       [-1.29439496,  0.49559543,  0.77644437,  0.1734185 ],
       [ 0.72545882,  0.73304379,  1.32608389,  0.28547859],
       [ 1.66439334, -0.63226935, -1.04067891, -0.1789704 ]])

In [203]:
arr > 0#0보다 큰 인자에서는 True를 반환한다

array([[ True,  True, False,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [204]:
arr * arr>0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [205]:
np.where(arr>0,2,-2)

array([[ 2,  2, -2,  2],
       [-2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2, -2, -2, -2]])

In [206]:
np.where(arr>0, 2, arr)#True -> 2, False -> arr

array([[ 2.        ,  2.        , -1.92921577,  2.        ],
       [-1.29439496,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        , -0.63226935, -1.04067891, -0.1789704 ]])

In [207]:
arr = np.random.randn(5,4)

In [208]:
arr

array([[ 1.05109337,  0.67210334,  0.74834361, -0.84416258],
       [ 0.03783099, -1.12678231, -1.724081  , -2.17221278],
       [-0.47121106,  1.18299332, -0.75003347,  1.16946057],
       [ 0.47678747,  0.59826217, -0.52607876,  0.91936637],
       [-0.36224311,  0.76936153,  0.09258811,  1.77936398]])

In [209]:
arr.mean()

0.07603748800238232

In [211]:
np.mean(arr)

0.07603748800238232

In [213]:
arr.sum()

1.5207497600476463

In [214]:
arr.mean(axis=1)

array([ 0.40684444, -1.24631127,  0.28280234,  0.36708431,  0.56976763])

In [215]:
arr.mean(axis=0)

array([ 0.14645153,  0.41918761, -0.4318523 ,  0.17036311])

In [216]:
arr.sum(axis=0)

array([ 0.73225765,  2.09593806, -2.1592615 ,  0.85181555])

In [217]:
arr.sum(axis=1)

array([ 1.62737774, -4.9852451 ,  1.13120936,  1.46833725,  2.2790705 ])

In [218]:
arr

array([[ 1.05109337,  0.67210334,  0.74834361, -0.84416258],
       [ 0.03783099, -1.12678231, -1.724081  , -2.17221278],
       [-0.47121106,  1.18299332, -0.75003347,  1.16946057],
       [ 0.47678747,  0.59826217, -0.52607876,  0.91936637],
       [-0.36224311,  0.76936153,  0.09258811,  1.77936398]])

In [220]:
arr = np.array([0,1,2,3,4,5,6,7])
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [221]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [223]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [224]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [225]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [226]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [227]:
arr.cumprod(axis=0)#누적 곱

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]])

In [232]:
arr = np.random.randn(100)
(arr>0).sum()

41

In [233]:
bools = np.array([False, True, False])
bools.any()

True

In [234]:
bools.all()

False

In [235]:
arr = np.random.randn(6)
arr

array([-0.93493692, -0.64471564, -0.86857669, -0.61769489,  0.53155398,
       -1.33736313])

In [236]:
arr.sort()

In [239]:
arr = np.random.randn(5,3)

In [242]:
arr.sort(1)
arr#각row에 맞춰서 sort

array([[-0.93796698, -0.90023705,  0.54820324],
       [ 0.88354962,  0.96598974,  1.14658731],
       [ 0.32943077,  1.09277568,  1.18646182],
       [-1.77918916, -0.23708829, -0.22880572],
       [-1.98393946, -0.41826177, -0.17864367]])

In [243]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [244]:
ints = np.array([3,3,3,2,2,2,1,1,4,4])

In [245]:
np.unique(ints)

array([1, 2, 3, 4])

In [ ]:
value = np.array([6,0,0,3,2,5,6])

In [250]:
sample = np.random.normal(size=(4,4))

In [251]:
sample

array([[ 0.76988996, -1.68614209, -0.73731474,  2.12771351],
       [ 1.40002874,  0.48611312, -2.74988648,  0.5507063 ],
       [-0.66697014,  0.76044941, -0.36383509, -1.27354911],
       [ 0.80756036,  1.14115626, -0.78337729, -0.22516955]])